// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egqohdrqvcemuzkyijoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncW9oZHJxdmNlbXV6a3lpam9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzY5MjUsImV4cCI6MjA2OTY1MjkyNX0.8RhyU-wR5DfPNm1BDrRUHwHT9jUs7T0zgxS6fspe2oU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});